spring.datasource.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/wallethub?createDatabaseIfNotExist=true&useSSL=false"
spring.datasource.username: "Juan.Valero"
spring.datasource.password: "cpx5842698"
spring.liquibase.change-log: "classpath:/db.wallehub-1.0.xml"
requestDate.format: "yyyy-MM-dd HH:mm:ss"
inputDate.format: "yyyy-MM-dd.HH:mm:ss"
queryDate.format: "%Y-%d-%m.%T"
accesslog: ".//access.log"
logging.level.org.springframework: "ERROR"
logging.level.org.springframework.batch.core.job: "INFO"
logging.level.com.zaxxer.hikari.HikariDataSource: "ERROR"
